### ISSUE TITLE
Height Calculation Task 5

### ISSUE THREAD

**Issue by Pablo-Paniagua** [Digital-Humans-23/a1#14]
As discussed during the lecture, I was wondering if the adjustment needed for task 5 on the ground height has to be "hard coded" from the sphere's information or if there is a function you could point me/us to. I was expecting there to be a function to get the height in world frame from a point in the mesh, but could not find anything that seemed to work.
This also makes me wonder if adding the sphere is enough for it to be added to the ground mesh as a single unit or if an additional step is required for that?

Thanks in advance.

**Comment by eastskykang** [comment]
Hi Pablo, 

Yes, for this purpose, I'd recommend you to use the following function.

```cpp
// member function of Model class
bool Model::hitByRay(const P3D &r_o, const V3D &r_v, P3D &hitPoint) const;
```

Basically, this function shoots a ray from the source ```r_o``` in the direction of ```r_v``` and returns intersecting point ```hitPoint```.

Let's say you want to get a height of the ground at 2D point (x, z). Then you can shoot a ray from (x, 10, z) (10 is just an example...) in the direction of (0, -1, 0) and retrieve the y component of ```hitPoint```.

Hope this helps!

Note. here, you may notice the argument of the function ```hitPoint``` is a non-const **reference**. Once you pass some ```P3D``` variable as an argument, after calling this function, the variable will contains the actual value of the hit point i.e. 

```cpp
P3D hitpoint;
hitByRay(P3D(x, 10, z), V3D(0, -1, 0), hitPoint);
// at this point, hitpoint contains the value of the position of hit point.
```

**Comment by xiyichen** [comment]
@eastskykang I tried hitByRay for multiple random (x, z) but it always returned false. What can could possibly get wrong?

**Comment by xiyichen** [comment]
nvm, turns out I didn't use the correct sphere model object.
