### ISSUE TITLE
Ex3 headingAngle

### ISSUE THREAD

**Issue by billyzs** [Digital-Humans-23/a1#5]
I'm not sure if I understand what `headingAngle` is supposed to achieve.

1. Suppose fwd and sideways speeds are both 0, while turning speed is positive. is the robot supposed to rotate ccw in place?
2. I find one of the hint a bit cryptic: "`quaternion heading = Roty(headingAngle). (we use y-up world frame coordinate)`". What is `Roty`? And what does quaternion have to do with this?
3. do we need to make sure headingAngle stays within [0, 360)?
4. and just to be sure, headingAngle is expressed in angle, not radian?
5. A specific symptom I'm struggling with is, my code behaves fine with fwd and sideways velocity turned on, but as soon as turning speed is turned on, the controller commands are garbage: 
![image](https://user-images.githubusercontent.com/5483052/222554540-c87ada31-448f-496c-b03b-95688063e67d.png)
I'm not sure where the problem is. Looks like the planner is also doing the right thing for my interpretation of turning speed. Since my code works with fwd and sideways speed, FK and IK should be reasonable, but still could have bugs. I'm out of ideas to try...

**Comment by billyzs** [comment]
I narrowed down the problem in 5) to IK; I am missing the final rotation from robot's root to world frame. But new question:
6) How are q[3], q[4], q[5] parameterized? Is it a specific Euler angle arrangement? Without this we would have to try blindly, which isn't fun.

**Comment by eastskykang** [comment]
You can consider the heading angle as the yaw angle of the robot's base. Thus, starting from the current yaw angle, which is computed by line 216,

```cpp
double headingAngle = startingbFrameState[3];
```

you can just increment the heading angle according to the turning speed (think about how much you have to increment it for a single iteration.)


Here are answers for your questions.

1. yes. If forward, sideways speed commands are zero, and turning speed command is > 0 then the robot has to rotate in ccw in place.
2. actually, you don't have to do anything for updating quaternion. The following code in line 231 exactly does that for you 
```cpp
Quaternion heading = getRotationQuaternion(headingAngle, V3D(0, 1, 0));
```
nevertheless, if you are curious what ```Roty``` is, it is the quaternion corresponds to rotation around y axis. If a given heading angle is theta, the quaternion corresponds to theta is ```[w, x, y, z] = [cos(theta/2), 0, sin(theta/2), 0]```. If you want to learn more about quaternion, I made a very brief introduction [here](https://github.com/Digital-Humans-23/a1/issues/1), so please take a look.
3. in short, that is not necessary.
4. heading angle should be in rad unit and turning speed should be in rad/s.

I believe your follow up questions 5, 6 can be also answered by these answers.

**Comment by billyzs** [comment]
Thanks for your help, yes this answers all my questions except I'm still not sure about 6) - the parameterization of rotation. From your response I can see that to apply the correct rotation from base to world, I just have to rotate points in base's frame by `rotateVec(p, q[3], V3D{0,1,0})`. But doesn't this assume that the base's y axis is always aligned with the world y axis? Once we add uneven terrain like in the bonus task this would not hold, we still need to know how the other axis (q[4], q[5]) are parameterized and apply the right rotation, is that right?

**Comment by eastskykang** [comment]
Oh I'm sorry I misunderstood your question 6. 

For generalized coordinates robot representation, you should also take into account pitch and roll angle of the base. The parameterization of the rotation part (q[3], q[4], q[5]) is yaw-pitch-roll angles. 

Since we use y-up, z-forward coordinate frame convention, 

R_base = R_y(q[3]) x R_x(q[4]) x R_z(q[5])

where R_y, R_x, R_z are rotation around y, x, z axes respectively. 

I believe my [tutorial slide](https://moodle-app2.let.ethz.ch/pluginfile.php/1517852/mod_folder/content/0/Digital-Humans-23-a1_1.pdf?forcedownload=1) slide no.30 could be helpful for you.
