### ISSUE TITLE
Sideways direction

### ISSUE THREAD

**Issue by juhe9842** [Digital-Humans-23/a1#6]
Hello, 

Might be a dumb question but I just wanted to make sure if I understand the slides correctly. The positive sideways direction is to the left as seen from the robot perspective right? Namely if I set the sideways velocity to 1m/s the robot goes to its left?

**Comment by eastskykang** [comment]
Yes. I know it's a bit confusing, but we use y-up and z-forward axes coordinate system. 

Thus, in robot base's coordinate frame, x axis (sideways-axis) is toward left side of the robot.

**Comment by xuexianlim** [comment]
It seems that when I use the hints for Ex 3 (Trajectory Planning), the vectors robot->forward and RBGlobals::worldUp.cross(robot->forward) are always expressed in the world frame so in the app, increasing these will always cause the robot to go in the same direction even if I change the robot's heading (changing the heading causes the robot to still traverse the same trajectory but it starts spinning while doing so). Is this correct or is there something I am missing?
