### ISSUE TITLE
Segmentation fault when closing the app

### ISSUE THREAD

**Issue by emilia-szymanska** [Digital-Humans-23/a1#8]
It is not critical, but there is a segfault when I quit the app (I am on Linux) by either pressing ESC or clicking the close button. I cloned the original repository and after the first build, without applying any changes to the code, I still get the segfault.

**Comment by eastskykang** [comment]
Thank you so much for reporting. Somehow this is not reproducible on mac, but I remember I also had a similar issue on Linux machine. 

Let me test it on Linux and get back to you.

**Comment by eastskykang** [comment]
Hi, 

I confirm our GUI code raises segmentation fault when a window is terminated. We figured out why it happens, but it requires pretty significant code modification. So let's just stick to it for this assignment.
