### ISSUE TITLE
Do not use getRotationAngle(qRel, axis)

### ISSUE THREAD

**Issue by bottad** [Digital-Humans-23/a1#9]
Do not use the member function of the joint class to get its current rotation as it does not return the updated angle.

**Comment by eastskykang** [comment]
Thank you @bottad. 

Yes, I'd better to mention this. The ```GeneralizedCoordinatesRobotRepresenetation``` does not automatically synchronize q and qdot with the robot. 

That means, for computing Jacobian with FD, you should not use current joint angle retrieved from the robot by ```getRotationAngle(qRel, axis)``` but rather, you have to retrieve it from the member variable ```q```.

It's better for you to stick to use helper functions and member variables of ```GeneralizedCoordinatesRobotRepresenetation``` when you implement FK, and Jacobians.
